apiVersion: v1
kind: ConfigMap
metadata:
  name: s3proxy-config
  namespace: aaw-fc
  labels:
    app: s3proxy
data:
  #S3PROXY_AUTHORIZATION: "none"
  S3PROXY_CORS_ALLOW_ALL: "true"
  S3PROXY_ENDPOINT: "http://0.0.0.0:9000"
  S3PROXY_IGNORE_UNKNOWN_HEADERS: "true"
  S3PROXY_AUTHORIZATION: none
  JCLOUDS_PROVIDER: filesystem
  JCLOUDS_FILESYSTEM_BASEDIR: /home/jovyan/buckets
