apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy
  namespace: aaw-fc
  labels:
    app: s3proxy
spec:
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      annotations:
        data.statcan.gc.ca/inject-blob-volumes: "true"
      labels:
        app: s3proxy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: s3proxy
          # image: k8scc01covidacr.azurecr.io/s3proxy:a73c4de9a715e6d5760616465bbaf9256995bb3e
          image: k3d-s3proxy-registry:5050/s3proxy-dev:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: s3proxy-config
          ports:
            - name: http
              containerPort: 9000
        - name: nginx
          image: docker.io/nginxinc/nginx-unprivileged:1.21-alpine
          resources:
            limits:
              cpu: "0.25"
              memory: "250Mi"
            requests:
              cpu: "0.25"
              memory: "250Mi"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: static-files
              mountPath: /etc/nginx/html/
          ports:
            - name: http
              containerPort: 8080
      initContainers:
        - name: copy-vendor-static-files
          # image: k8scc01covidacr.azurecr.io/s3proxy:a73c4de9a715e6d5760616465bbaf9256995bb3e
          image: k3d-s3proxy-registry:5050/s3proxy-dev:latest
          command: [bash, -c]
          args: ["cp -r /etc/static/* /etc/nginx/html/"]
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/nginx/html/
              name: static-files
      volumes:
        - name: nginx-config
          configMap:
            name: s3proxy-nginx-conf
        - name: static-files
          emptyDir: {}
